use super::Cpu;

pub enum Operation {
    BRK,
    ORA,
    ASL,
    PHP,
    BPL,
    CLC,
    JSR,
    AND,
    BIT,
    ROL,
    PLP,
    BMI,
    SEC,
    RTI,
    EOR,
    LSR,
    PHA,
    JMP,
    BVC,
    CLI,
    RTS,
    ADC,
    ROR,
    PLA,
    STA,
    STY,
    STX,
    DEY,
    TXA,
    BCC,
    INC,
    SBC,
    SEI,
    BVS,
    TYA,
    TXS,
    LDY,
    LDA,
    LDX,
    TAY,
    TAX,
    BCS,
    CLV,
    TSX,
    CPY,
    CMP,
    DEX,
    DEC,
    INY,
    BNE,
    CLD,
    CPX,
    INX,
    NOP,
    BEQ,
    SED,
    UnknownOperation
}

pub enum AddressingMode {
  Implied,
  Immediate,
  ZeroPage,
  ZeroPageX,
  ZeroPageY,
  Relative,
  Absolute,
  AbsoluteX,
  AbsoluteY,
  Indirect,
  IndirectX,
  IndirectY,
  Accumulator,
}

pub struct Instruction {
    pub operation: Operation,
    pub address_mode: AddressingMode,
    pub cycles: u8
}

impl Cpu {
    fn load_instruction_data(&mut self, instruction: &Instruction) -> (u8, u8){
        match instruction.address_mode {
            AddressingMode::Implied => (0, 0),
            AddressingMode::Immediate => {
                let value = self.bus.read(self.pc);
                self.pc += 1;
                (value, 0)
            },
            AddressingMode::ZeroPage => {
                let address = self.bus.read(self.pc);
                self.pc += 1;
                let value = self.bus.read(u16::from(address));
                (value, 0)
            },
            AddressingMode::ZeroPageX => todo!(),
            AddressingMode::ZeroPageY => todo!(),
            AddressingMode::Relative => todo!(),
            AddressingMode::Absolute => todo!(),
            AddressingMode::AbsoluteX => todo!(),
            AddressingMode::AbsoluteY => todo!(),
            AddressingMode::Indirect => todo!(),
            AddressingMode::IndirectX => todo!(),
            AddressingMode::IndirectY => todo!(),
            AddressingMode::Accumulator => todo!(),
        }
    }

    fn execute_instruction(&mut self, instruction: &Instruction) {

    }
}

impl Instruction {
  pub fn from_u8(value: u8) -> Instruction {
    return match value {
      // 0x0*
      0x00 => Instruction { operation: Operation::BRK, address_mode: AddressingMode::Implied,      cycles: 7 },
      0x01 => Instruction { operation: Operation::ORA, address_mode: AddressingMode::IndirectX,    cycles: 6 },
      0x05 => Instruction { operation: Operation::ORA, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0x06 => Instruction { operation: Operation::ASL, address_mode: AddressingMode::ZeroPage,     cycles: 5 },
      0x08 => Instruction { operation: Operation::PHP, address_mode: AddressingMode::Implied,      cycles: 3 },
      0x09 => Instruction { operation: Operation::ORA, address_mode: AddressingMode::Immediate,    cycles: 2 },
      0x0A => Instruction { operation: Operation::ASL, address_mode: AddressingMode::Accumulator,  cycles: 2 },
      0x0D => Instruction { operation: Operation::ORA, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0x0E => Instruction { operation: Operation::ASL, address_mode: AddressingMode::Absolute,     cycles: 6 },
      // 0x1*
      0x10 => Instruction { operation: Operation::BPL, address_mode: AddressingMode::Relative,     cycles: 2 },
      0x11 => Instruction { operation: Operation::ORA, address_mode: AddressingMode::IndirectY,     cycles: 5 },
      0x15 => Instruction { operation: Operation::ORA, address_mode: AddressingMode::ZeroPageX,    cycles: 4 },
      0x16 => Instruction { operation: Operation::ASL, address_mode: AddressingMode::ZeroPageX,    cycles: 6 },
      0x18 => Instruction { operation: Operation::CLC, address_mode: AddressingMode::Implied,      cycles: 2 },
      0x19 => Instruction { operation: Operation::ORA, address_mode: AddressingMode::AbsoluteY,    cycles: 4 },
      0x1D => Instruction { operation: Operation::ORA, address_mode: AddressingMode::AbsoluteX,    cycles: 4 },
      0x1E => Instruction { operation: Operation::ASL, address_mode: AddressingMode::AbsoluteX,    cycles: 7 },
      // 0x2*
      0x20 => Instruction { operation: Operation::JSR, address_mode: AddressingMode::Absolute,     cycles: 6 },
      0x21 => Instruction { operation: Operation::AND, address_mode: AddressingMode::IndirectX,     cycles: 6 },
      0x24 => Instruction { operation: Operation::BIT, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0x25 => Instruction { operation: Operation::AND, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0x26 => Instruction { operation: Operation::ROL, address_mode: AddressingMode::ZeroPage,     cycles: 5 },
      0x28 => Instruction { operation: Operation::PLP, address_mode: AddressingMode::Implied,      cycles: 4 },
      0x29 => Instruction { operation: Operation::AND, address_mode: AddressingMode::Immediate,    cycles: 2 },
      0x2A => Instruction { operation: Operation::ROL, address_mode: AddressingMode::Accumulator,  cycles: 2 },
      0x2C => Instruction { operation: Operation::BIT, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0x2D => Instruction { operation: Operation::AND, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0x2E => Instruction { operation: Operation::ROL, address_mode: AddressingMode::Absolute,     cycles: 6 },
      // 0x3*
      0x30 => Instruction { operation: Operation::BMI, address_mode: AddressingMode::Relative,     cycles: 2 },
      0x31 => Instruction { operation: Operation::AND, address_mode: AddressingMode::IndirectY,     cycles: 5 },
      0x35 => Instruction { operation: Operation::AND, address_mode: AddressingMode::ZeroPageX,    cycles: 4 },
      0x36 => Instruction { operation: Operation::ROL, address_mode: AddressingMode::ZeroPageX,    cycles: 6 },
      0x38 => Instruction { operation: Operation::SEC, address_mode: AddressingMode::Implied,      cycles: 2 },
      0x39 => Instruction { operation: Operation::AND, address_mode: AddressingMode::AbsoluteY,    cycles: 4 },
      0x3D => Instruction { operation: Operation::AND, address_mode: AddressingMode::AbsoluteX,    cycles: 4 },
      0x3E => Instruction { operation: Operation::ROL, address_mode: AddressingMode::AbsoluteX,    cycles: 7 },
      // 0x4*
      0x40 => Instruction { operation: Operation::RTI, address_mode: AddressingMode::Implied,      cycles: 6 },
      0x41 => Instruction { operation: Operation::EOR, address_mode: AddressingMode::IndirectX,     cycles: 6 },
      0x45 => Instruction { operation: Operation::EOR, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0x46 => Instruction { operation: Operation::LSR, address_mode: AddressingMode::ZeroPage,     cycles: 5 },
      0x48 => Instruction { operation: Operation::PHA, address_mode: AddressingMode::Implied,      cycles: 3 },
      0x49 => Instruction { operation: Operation::EOR, address_mode: AddressingMode::Immediate,    cycles: 2 },
      0x4A => Instruction { operation: Operation::LSR, address_mode: AddressingMode::Accumulator,  cycles: 2 },
      0x4C => Instruction { operation: Operation::JMP, address_mode: AddressingMode::Absolute,     cycles: 3 },
      0x4D => Instruction { operation: Operation::EOR, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0x4E => Instruction { operation: Operation::LSR, address_mode: AddressingMode::Absolute,     cycles: 6 },
      // 0x5*
      0x50 => Instruction { operation: Operation::BVC, address_mode: AddressingMode::Relative,     cycles: 2 },
      0x51 => Instruction { operation: Operation::EOR, address_mode: AddressingMode::IndirectY,     cycles: 5 },
      0x55 => Instruction { operation: Operation::EOR, address_mode: AddressingMode::ZeroPageX,    cycles: 4 },
      0x56 => Instruction { operation: Operation::LSR, address_mode: AddressingMode::ZeroPageX,    cycles: 6 },
      0x58 => Instruction { operation: Operation::CLI, address_mode: AddressingMode::Implied,      cycles: 2 },
      0x59 => Instruction { operation: Operation::EOR, address_mode: AddressingMode::AbsoluteY,    cycles: 4 },
      0x5D => Instruction { operation: Operation::EOR, address_mode: AddressingMode::AbsoluteX,    cycles: 4 },
      0x5E => Instruction { operation: Operation::LSR, address_mode: AddressingMode::AbsoluteX,    cycles: 7 },
      // 0x6*
      0x60 => Instruction { operation: Operation::RTS, address_mode: AddressingMode::Implied,      cycles: 6 },
      0x61 => Instruction { operation: Operation::ADC, address_mode: AddressingMode::IndirectX,     cycles: 6 },
      0x65 => Instruction { operation: Operation::ADC, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0x66 => Instruction { operation: Operation::ROR, address_mode: AddressingMode::ZeroPage,     cycles: 5 },
      0x68 => Instruction { operation: Operation::PLA, address_mode: AddressingMode::Implied,      cycles: 4 },
      0x69 => Instruction { operation: Operation::ADC, address_mode: AddressingMode::Immediate,    cycles: 2 },
      0x6A => Instruction { operation: Operation::ROR, address_mode: AddressingMode::Accumulator,  cycles: 2 },
      0x6C => Instruction { operation: Operation::JMP, address_mode: AddressingMode::Indirect,     cycles: 5 },
      0x6D => Instruction { operation: Operation::ADC, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0x6E => Instruction { operation: Operation::ROR, address_mode: AddressingMode::Absolute,     cycles: 6 },
      // 0x7*
      0x70 => Instruction { operation: Operation::BVS, address_mode: AddressingMode::Relative,     cycles: 2 },
      0x71 => Instruction { operation: Operation::ADC, address_mode: AddressingMode::IndirectY,     cycles: 5 },
      0x75 => Instruction { operation: Operation::ADC, address_mode: AddressingMode::ZeroPageX,    cycles: 4 },
      0x76 => Instruction { operation: Operation::ROR, address_mode: AddressingMode::ZeroPageX,    cycles: 6 },
      0x78 => Instruction { operation: Operation::SEI, address_mode: AddressingMode::Implied,      cycles: 2 },
      0x79 => Instruction { operation: Operation::ADC, address_mode: AddressingMode::AbsoluteY,    cycles: 4 },
      0x7D => Instruction { operation: Operation::ADC, address_mode: AddressingMode::AbsoluteX,    cycles: 4 },
      0x7E => Instruction { operation: Operation::ROR, address_mode: AddressingMode::AbsoluteX,    cycles: 7 },
      // 0x8*
      0x81 => Instruction { operation: Operation::STA, address_mode: AddressingMode::IndirectX,    cycles: 6 },
      0x84 => Instruction { operation: Operation::STY, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0x85 => Instruction { operation: Operation::STA, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0x86 => Instruction { operation: Operation::STX, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0x88 => Instruction { operation: Operation::DEY, address_mode: AddressingMode::Implied,      cycles: 2 },
      0x8A => Instruction { operation: Operation::TXA, address_mode: AddressingMode::Implied,      cycles: 2 },
      0x8C => Instruction { operation: Operation::STY, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0x8D => Instruction { operation: Operation::STA, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0x8E => Instruction { operation: Operation::STX, address_mode: AddressingMode::Absolute,     cycles: 4 },
      // 0x9*
      0x90 => Instruction { operation: Operation::BCC, address_mode: AddressingMode::Relative,     cycles: 2 },
      0x91 => Instruction { operation: Operation::STA, address_mode: AddressingMode::IndirectY,    cycles: 6 },
      0x94 => Instruction { operation: Operation::STY, address_mode: AddressingMode::ZeroPageX,    cycles: 4 },
      0x95 => Instruction { operation: Operation::STA, address_mode: AddressingMode::ZeroPageX,    cycles: 4 },
      0x96 => Instruction { operation: Operation::STX, address_mode: AddressingMode::ZeroPageY,    cycles: 4 },
      0x98 => Instruction { operation: Operation::TYA, address_mode: AddressingMode::Implied,      cycles: 2 },
      0x99 => Instruction { operation: Operation::STA, address_mode: AddressingMode::AbsoluteY,    cycles: 5 },
      0x9A => Instruction { operation: Operation::TXS, address_mode: AddressingMode::Implied,      cycles: 2 },
      0x9D => Instruction { operation: Operation::STA, address_mode: AddressingMode::AbsoluteX,    cycles: 5 },
      // 0xA*
      0xA0 => Instruction { operation: Operation::LDY, address_mode: AddressingMode::Immediate,    cycles: 2 },
      0xA1 => Instruction { operation: Operation::LDA, address_mode: AddressingMode::IndirectX,    cycles: 6 },
      0xA2 => Instruction { operation: Operation::LDX, address_mode: AddressingMode::Immediate,    cycles: 2 },
      0xA4 => Instruction { operation: Operation::LDY, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0xA5 => Instruction { operation: Operation::LDA, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0xA6 => Instruction { operation: Operation::LDX, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0xA8 => Instruction { operation: Operation::TAY, address_mode: AddressingMode::Implied,      cycles: 2 },
      0xA9 => Instruction { operation: Operation::LDA, address_mode: AddressingMode::Immediate,    cycles: 2 },
      0xAA => Instruction { operation: Operation::TAX, address_mode: AddressingMode::Implied,      cycles: 2 },
      0xAC => Instruction { operation: Operation::LDY, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0xAD => Instruction { operation: Operation::LDA, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0xAE => Instruction { operation: Operation::LDX, address_mode: AddressingMode::Absolute,     cycles: 4 },
      // 0xB*
      0xB0 => Instruction { operation: Operation::BCS, address_mode: AddressingMode::Relative,     cycles: 2 },
      0xB1 => Instruction { operation: Operation::LDA, address_mode: AddressingMode::IndirectY,    cycles: 5 },
      0xB4 => Instruction { operation: Operation::LDY, address_mode: AddressingMode::ZeroPageX,    cycles: 4 },
      0xB5 => Instruction { operation: Operation::LDA, address_mode: AddressingMode::ZeroPageX,    cycles: 4 },
      0xB6 => Instruction { operation: Operation::LDX, address_mode: AddressingMode::ZeroPageY,    cycles: 4 },
      0xB8 => Instruction { operation: Operation::CLV, address_mode: AddressingMode::Implied,      cycles: 2 },
      0xB9 => Instruction { operation: Operation::LDA, address_mode: AddressingMode::AbsoluteY,    cycles: 4 },
      0xBA => Instruction { operation: Operation::TSX, address_mode: AddressingMode::Implied,      cycles: 2 },
      0xBC => Instruction { operation: Operation::LDY, address_mode: AddressingMode::AbsoluteX,    cycles: 4 },
      0xBD => Instruction { operation: Operation::LDA, address_mode: AddressingMode::AbsoluteX,    cycles: 4 },
      0xBE => Instruction { operation: Operation::LDX, address_mode: AddressingMode::AbsoluteY,    cycles: 4 },
      // 0xC*
      0xC0 => Instruction { operation: Operation::CPY, address_mode: AddressingMode::Immediate,    cycles: 2 },
      0xC1 => Instruction { operation: Operation::CMP, address_mode: AddressingMode::IndirectX,    cycles: 6 },
      0xC4 => Instruction { operation: Operation::CPY, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0xC5 => Instruction { operation: Operation::CMP, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0xC6 => Instruction { operation: Operation::DEC, address_mode: AddressingMode::ZeroPage,     cycles: 5 },
      0xC8 => Instruction { operation: Operation::INY, address_mode: AddressingMode::Implied,      cycles: 2 },
      0xC9 => Instruction { operation: Operation::CMP, address_mode: AddressingMode::Immediate,    cycles: 2 },
      0xCA => Instruction { operation: Operation::DEX, address_mode: AddressingMode::Implied,      cycles: 2 },
      0xCC => Instruction { operation: Operation::CPY, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0xCD => Instruction { operation: Operation::CMP, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0xCE => Instruction { operation: Operation::DEC, address_mode: AddressingMode::Absolute,     cycles: 6 },
      // 0xD*
      0xD0 => Instruction { operation: Operation::BNE, address_mode: AddressingMode::Relative,     cycles: 2 },
      0xD1 => Instruction { operation: Operation::CMP, address_mode: AddressingMode::IndirectY,    cycles: 5 },
      0xD5 => Instruction { operation: Operation::CMP, address_mode: AddressingMode::ZeroPageX,    cycles: 4 },
      0xD6 => Instruction { operation: Operation::DEC, address_mode: AddressingMode::ZeroPageX,    cycles: 6 },
      0xD8 => Instruction { operation: Operation::CLD, address_mode: AddressingMode::Implied,      cycles: 2 },
      0xD9 => Instruction { operation: Operation::CMP, address_mode: AddressingMode::AbsoluteY,    cycles: 4 },
      0xDD => Instruction { operation: Operation::CMP, address_mode: AddressingMode::AbsoluteX,    cycles: 4 },
      0xDE => Instruction { operation: Operation::DEC, address_mode: AddressingMode::AbsoluteX,    cycles: 7 },
      // 0xE*
      0xE0 => Instruction { operation: Operation::CPX, address_mode: AddressingMode::Immediate,    cycles: 2 },
      0xE1 => Instruction { operation: Operation::SBC, address_mode: AddressingMode::IndirectX,    cycles: 6 },
      0xE4 => Instruction { operation: Operation::CPX, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0xE5 => Instruction { operation: Operation::SBC, address_mode: AddressingMode::ZeroPage,     cycles: 3 },
      0xE6 => Instruction { operation: Operation::INC, address_mode: AddressingMode::ZeroPage,     cycles: 5 },
      0xE8 => Instruction { operation: Operation::INX, address_mode: AddressingMode::Implied,      cycles: 2 },
      0xE9 => Instruction { operation: Operation::SBC, address_mode: AddressingMode::Immediate,    cycles: 2 },
      0xEA => Instruction { operation: Operation::NOP, address_mode: AddressingMode::Implied,      cycles: 2 },
      0xEC => Instruction { operation: Operation::CPX, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0xED => Instruction { operation: Operation::SBC, address_mode: AddressingMode::Absolute,     cycles: 4 },
      0xEE => Instruction { operation: Operation::INC, address_mode: AddressingMode::Absolute,     cycles: 6 },
      // 0xF*
      0xF0 => Instruction { operation: Operation::BEQ, address_mode: AddressingMode::Relative,     cycles: 2 },
      0xF1 => Instruction { operation: Operation::SBC, address_mode: AddressingMode::IndirectY,    cycles: 5 },
      0xF5 => Instruction { operation: Operation::SBC, address_mode: AddressingMode::ZeroPageX,    cycles: 4 },
      0xF6 => Instruction { operation: Operation::INC, address_mode: AddressingMode::ZeroPageX,    cycles: 6 },
      0xF8 => Instruction { operation: Operation::SED, address_mode: AddressingMode::Implied,      cycles: 2 },
      0xF9 => Instruction { operation: Operation::SBC, address_mode: AddressingMode::AbsoluteY,    cycles: 4 },
      0xFD => Instruction { operation: Operation::SBC, address_mode: AddressingMode::AbsoluteX,    cycles: 4 },
      0xFE => Instruction { operation: Operation::INC, address_mode: AddressingMode::AbsoluteX,    cycles: 7 },
      _    => Instruction { operation: Operation::NOP, address_mode: AddressingMode::Implied,      cycles: 0 }
    }
  }
}
